INSERT INTO APP_USER (USERNAME, PASSWORD, CREATED) VALUES ('admin', 'password', '2025-04-17 15:55:12');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE) VALUES (0, 'Rainer', 'Zufall', 'rainer.zufall@gmail.com', '0512 1234567');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE) VALUES (1, 'Max', 'Mustermann', 'max.mustermann@gmail.com', '0512 9876543');